=== oalam/tps/HaricotAimable/setup/haricot.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 (http://www.altova.com) by plouk (plik) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="haricot">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="order" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="category" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name"/>
							<xs:element ref="product" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
						<xs:attribute name="id" type="xs:ID"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="product">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string"/>
				<xs:element name="price" type="xs:double"/>
				<xs:element name="stock_quantity" type="xs:int"/>
				<xs:element name="description" type="xs:string"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:ID"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="order">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="order_date" type="xs:dateTime"/>
				<xs:element name="confirmation_number" type="xs:string"/>
				<xs:element name="is_shipped" type="xs:boolean" default="false"/>
				<xs:element name="amount" type="xs:double"/>
				<xs:element name="ordered_product">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="product_id" type="xs:IDREF"/>
							<xs:element name="quantity" type="xs:int"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="customer">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string"/>
							<xs:element name="birth_date" type="xs:date"/>
							<xs:element name="address" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="id" type="xs:ID"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== oalam/tps/HaricotAimable/src/integration/xml/haricot.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 (http://www.altova.com) by plouk (plik) -->
<!--Sample XML file generated by XMLSpy v2013 (http://www.altova.com)-->
<haricot xsi:noNamespaceSchemaLocation="haricot.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<order id="ID_1">
		<order_date>2001-12-16T09:30:47Z</order_date>
		<confirmation_number>944711a4b80dd20c46871b250affa57c</confirmation_number>
		<is_shipped>false</is_shipped>
		<amount>3.14159265358979E0</amount>
		<ordered_product>
			<product_id>ID_1</product_id>
			<quantity>3</quantity>
		</ordered_product>
		<customer>
			<name>Bill Gates</name>
			<birth_date>1967-08-13</birth_date>
			<address>rue des pieds 75002 Paris</address>
		</customer>
	</order>
	<order id="ID_2">
		<order_date>2001-12-17T09:35:47Z</order_date>
		<confirmation_number>b72f16fdb26264abc8622834be4b0f60</confirmation_number>
		<is_shipped>false</is_shipped>
		<amount>3.14159265358979E0</amount>
		<ordered_product>
			<product_id>ID_3</product_id>
			<quantity>2</quantity>
		</ordered_product>
		<customer>
			<name>Max linder</name>
			<birth_date>1967-08-13</birth_date>
			<address>rue de la paix 75014 Paris</address>
		</customer>
	</order>
	<order id="ID_3">
		<order_date>2001-12-17T10:30:47Z</order_date>
		<confirmation_number>633de4b0c14ca52ea2432a3c8a5c4c31</confirmation_number>
		<is_shipped>true</is_shipped>
		<amount>3.14159265358979E0</amount>
		<ordered_product>
			<product_id>ID_12</product_id>
			<quantity>5</quantity>
		</ordered_product>
		<customer>
			<name>Charlie chaplin</name>
			<birth_date>1967-08-13</birth_date>
			<address>avenue de mazargues 13015 Marseille</address>
		</customer>
	</order>
	<category id="ID_5">
		<name>dairies</name>
		<product id="ID_6">
			<name>Milk</name>
			<price>1.51</price>
			<stock_quantity>23</stock_quantity>
			<description>good for children</description>
		</product>
		<product id="ID_7">
			<name>Cream</name>
			<price>2.89</price>
			<stock_quantity>10</stock_quantity>
			<description>fat but tasty</description>
		</product>
		<product id="ID_8">
			<name>Yogourth</name>
			<price>2.59</price>
			<stock_quantity>9</stock_quantity>
			<description>healthy food</description>
		</product>
	</category>
	<category id="ID_10">
		<name>meat</name>
		<product id="ID_11">
			<name>Steack</name>
			<price>18.95</price>
			<stock_quantity>0</stock_quantity>
			<description>Rare cook please</description>
		</product>
		<product id="ID_12">
			<name>Lamb</name>
			<price>23.59</price>
			<stock_quantity>23</stock_quantity>
			<description>What about the cow ?</description>
		</product>
		<product id="ID_13">
			<name>Horse</name>
			<price>12.26</price>
			<stock_quantity>12</stock_quantity>
			<description>Delicious</description>
		</product>
	</category>
	<category id="ID_15">
		<name>vegetables</name>
		<product id="ID_16">
			<name>Tomato</name>
			<price>4.59</price>
			<stock_quantity>15</stock_quantity>
			<description>Don you know pomodor technique ?</description>
		</product>
		<product id="ID_17">
			<name>Egg plant</name>
			<price>3.98</price>
			<stock_quantity>13</stock_quantity>
			<description>why egg ?</description>
		</product>
		<product id="ID_18">
			<name>Salad</name>
			<price>2.35</price>
			<stock_quantity>10</stock_quantity>
			<description>Green is beautifull</description>
		</product>
		<product id="ID_19">
			<name>Pumpkin</name>
			<price>1.89</price>
			<stock_quantity>23</stock_quantity>
			<description>halloween soon ?</description>
		</product>
	</category>
	<category id="ID_20">
		<name>bakery</name>
		<product id="ID_21">
			<name>Bread</name>
			<price>2.59</price>
			<stock_quantity>12</stock_quantity>
			<description/>
		</product>
		<product id="ID_22">
			<name>Croissant</name>
			<price>095</price>
			<stock_quantity>15</stock_quantity>
			<description/>
		</product>
	</category>
</haricot>
